% Read the header of a P file (version 24).
% liuhang, 2018/6/

% Pfile = 'F:\sd\mri\header read\data\version 14\pfiles_name\pfiles_name\NoXdcr_TE7ms_P46592.7';
% fid=fopen(Pfile,'r', 'ieee-le');
% hdr = read_hdr_24(fid);

function hdr = read_hdr_24(fid)
fseek(fid, 0, 'bof');
hdr.version = fread(fid, 1, 'float');
fseek(fid, 12, 'cof');
hdr.scan_date = fread(fid, 10,'*char');
hdr.scan_time = fread(fid, 8,'*char');
fseek(fid, 30, 'cof');
hdr.npasses = fread(fid, 1, 'short');
fseek(fid, 2, 'cof');
hdr.nslices = fread(fid, 1, 'ushort');
hdr.nechoes = fread(fid, 1, 'short');
fseek(fid, 2, 'cof');
hdr.nframes = fread(fid, 1, 'short');
fseek(fid, 4, 'cof');
hdr.frame_size = fread(fid, 1, 'ushort');
fseek(fid, 20, 'cof');
hdr.acq_x_res = fread(fid, 1, 'ushort');
hdr.acq_y_res = fread(fid, 1, 'short');
hdr.recon_x_res = fread(fid, 1, 'short');
hdr.recon_y_res = fread(fid, 1, 'short');
hdr.im_size = fread(fid, 1, 'short');
hdr.recon_z_res = fread(fid, 1, 'int');
fseek(fid, 100, 'cof');
hdr.user0 = fread(fid, 1, 'float');
hdr.user1 = fread(fid, 1, 'float');
hdr.user2 = fread(fid, 1, 'float');
hdr.user3 = fread(fid, 1, 'float');
hdr.user4 = fread(fid, 1, 'float');
hdr.user5 = fread(fid, 1, 'float');
hdr.user6 = fread(fid, 1, 'float');
hdr.user7 = fread(fid, 1, 'float');
hdr.user8 = fread(fid, 1, 'float');
hdr.user9 = fread(fid, 1, 'float');
hdr.user10 = fread(fid, 1, 'float');
hdr.user11 = fread(fid, 1, 'float');
hdr.user12 = fread(fid, 1, 'float');
hdr.user13 = fread(fid, 1, 'float');
hdr.user14 = fread(fid, 1, 'float');
hdr.user15 = fread(fid, 1, 'float');
hdr.user16 = fread(fid, 1, 'float');
hdr.user17 = fread(fid, 1, 'float');
hdr.user18 = fread(fid, 1, 'float');
hdr.user19 = fread(fid, 1, 'float');
fseek(fid, 704, 'cof');
hdr.user20 = fread(fid, 1, 'float');
hdr.user21 = fread(fid, 1, 'float');
hdr.user22 = fread(fid, 1, 'float');
hdr.user23 = fread(fid, 1, 'float');
hdr.user24 = fread(fid, 1, 'float');
hdr.user25 = fread(fid, 1, 'float');
hdr.user26 = fread(fid, 1, 'float');
hdr.user27 = fread(fid, 1, 'float');
hdr.user28 = fread(fid, 1, 'float');
hdr.user29 = fread(fid, 1, 'float');
hdr.user30 = fread(fid, 1, 'float');
hdr.user31 = fread(fid, 1, 'float');
hdr.user32 = fread(fid, 1, 'float');
hdr.user33 = fread(fid, 1, 'float');
hdr.user34 = fread(fid, 1, 'float');
hdr.user35 = fread(fid, 1, 'float');
hdr.user36 = fread(fid, 1, 'float');
hdr.user37 = fread(fid, 1, 'float');
hdr.user38 = fread(fid, 1, 'float');
hdr.user39 = fread(fid, 1, 'float');
hdr.user40 = fread(fid, 1, 'float');
hdr.user41 = fread(fid, 1, 'float');
hdr.user42 = fread(fid, 1, 'float');
hdr.user43 = fread(fid, 1, 'float');
hdr.user44 = fread(fid, 1, 'float');
hdr.user45 = fread(fid, 1, 'float');
hdr.user46 = fread(fid, 1, 'float');
hdr.user47 = fread(fid, 1, 'float');
hdr.user48 = fread(fid, 1, 'float');
fseek(fid, 528, 'cof');
hdr.bandwidth = fread(fid, 1, 'float');
hdr.data_size = fread(fid, 1, 'ulong');
hdr.ssp_save = fread(fid, 1, 'ulong');
hdr.uda_save = fread(fid, 1, 'ulong');
fseek(fid, 139668, 'cof');
hdr.aps_r1 = fread(fid, 1, 'int');
hdr.aps_r2 = fread(fid, 1, 'int');
hdr.aps_tg = fread(fid, 1, 'int');
hdr.aps_frequency = fread(fid, 1, 'uint');
hdr.scale_i = fread(fid, 1, 'float');
hdr.scale_q = fread(fid, 1, 'float');
fseek(fid, 276, 'cof');
hdr.x_shim = fread(fid, 1, 'short');
hdr.y_shim = fread(fid, 1, 'short');
hdr.z_shim = fread(fid, 1, 'short');
hdr.recon_enabled = fread(fid, 1, 'short');
fseek(fid, 1744, 'cof');
hdr.magnet_strength = fread(fid, 1, 'int');
hdr.patient_weight_g = fread(fid, 1, 'int');
hdr.exam_timestamp = fread(fid, 1, 'int');
fseek(fid, 112, 'cof');
hdr.exam_number = fread(fid, 1, 'ushort');
fseek(fid, 18, 'cof');
hdr.patient_age = fread(fid, 1, 'short');
fseek(fid, 2, 'cof');
hdr.patient_sex = fread(fid, 1, 'short');
fseek(fid, 2, 'cof');
hdr.patient_trauma = fread(fid, 1, 'short');
fseek(fid, 2, 'cof');
hdr.study_status = fread(fid, 1, 'short');
fseek(fid, 70, 'cof');
hdr.history = fread(fid, 257, '*char');
hdr.referring_physicians_name = fread(fid, 65, '*char');
hdr.radiologists_name = fread(fid, 65, '*char');
hdr.operators_name = fread(fid, 65, '*char');
hdr.exam_description = fread(fid, 65, '*char');
hdr.exam_type = fread(fid, 3, '*char');
hdr.system_id = fread(fid, 9, '*char');
fseek(fid, 22, 'cof');
hdr.hospital_name = fread(fid, 33, '*char');
fseek(fid, 24, 'cof');
hdr.service_id = fread(fid, 16, '*char');
fseek(fid, 100, 'cof');
hdr.patient_name = fread(fid, 65, '*char');
hdr.patient_id = fread(fid, 65, '*char');
hdr.req_num = fread(fid, 17, '*char');
hdr.date_of_birth = fread(fid, 9, '*char');
fseek(fid, 552, 'cof');
hdr.start_location = fread(fid, 1, 'float');
hdr.end_location = fread(fid, 1, 'float');
fseek(fid, 352, 'cof');
hdr.series_timestamp = fread(fid, 1, 'int');
fseek(fid, 206, 'cof');
hdr.series_number = fread(fid, 1, 'short');
fseek(fid, 138, 'cof');
hdr.series_description = fread(fid, 65, '*char');
fseek(fid, 21, 'cof');
hdr.protocol = fread(fid, 25, '*char');
hdr.start_ras = fread(fid, 1, 'char');
hdr.end_ras = fread(fid, 1, 'char');
fseek(fid, 1769, 'cof');
hdr.x_field_of_view = fread(fid, 1, 'float');
hdr.y_field_of_view = fread(fid, 1, 'float');
hdr.scan_duration = fread(fid, 1, 'float');
hdr.z_thickness = fread(fid, 1, 'float');
fseek(fid, 36, 'cof');
hdr.op_user_0 = fread(fid, 1, 'float');
hdr.op_user_1 = fread(fid, 1, 'float');
hdr.op_user_2 = fread(fid, 1, 'float');
hdr.op_user_3 = fread(fid, 1, 'float');
hdr.op_user_4 = fread(fid, 1, 'float');
hdr.op_user_5 = fread(fid, 1, 'float');
hdr.op_user_6 = fread(fid, 1, 'float');
hdr.op_user_7 = fread(fid, 1, 'float');
hdr.op_user_8 = fread(fid, 1, 'float');
hdr.op_user_9 = fread(fid, 1, 'float');
hdr.op_user_10 = fread(fid, 1, 'float');
hdr.op_user_11 = fread(fid, 1, 'float');
hdr.op_user_12 = fread(fid, 1, 'float');
hdr.op_user_13 = fread(fid, 1, 'float');
hdr.op_user_14 = fread(fid, 1, 'float');
hdr.op_user_15 = fread(fid, 1, 'float');
hdr.op_user_16 = fread(fid, 1, 'float');
hdr.op_user_17 = fread(fid, 1, 'float');
hdr.op_user_18 = fread(fid, 1, 'float');
hdr.op_user_19 = fread(fid, 1, 'float');
hdr.op_user_20 = fread(fid, 1, 'float');
hdr.op_user_21 = fread(fid, 1, 'float');
hdr.op_user_22 = fread(fid, 1, 'float');
fseek(fid, 8, 'cof');
hdr.op_user_23 = fread(fid, 1, 'float');
hdr.op_user_24 = fread(fid, 1, 'float');
fseek(fid, 60, 'cof');
hdr.op_user_25 = fread(fid, 1, 'float');
hdr.op_user_26 = fread(fid, 1, 'float');
hdr.op_user_27 = fread(fid, 1, 'float');
hdr.op_user_28 = fread(fid, 1, 'float');
hdr.op_user_29 = fread(fid, 1, 'float');
hdr.op_user_30 = fread(fid, 1, 'float');
hdr.op_user_31 = fread(fid, 1, 'float');
hdr.op_user_32 = fread(fid, 1, 'float');
hdr.op_user_33 = fread(fid, 1, 'float');
hdr.op_user_34 = fread(fid, 1, 'float');
hdr.op_user_35 = fread(fid, 1, 'float');
hdr.op_user_36 = fread(fid, 1, 'float');
hdr.op_user_37 = fread(fid, 1, 'float');
hdr.op_user_38 = fread(fid, 1, 'float');
hdr.op_user_39 = fread(fid, 1, 'float');
hdr.op_user_40 = fread(fid, 1, 'float');
hdr.op_user_41 = fread(fid, 1, 'float');
hdr.op_user_42 = fread(fid, 1, 'float');
hdr.op_user_43 = fread(fid, 1, 'float');
hdr.op_user_44 = fread(fid, 1, 'float');
hdr.op_user_45 = fread(fid, 1, 'float');
hdr.op_user_46 = fread(fid, 1, 'float');
hdr.op_user_47 = fread(fid, 1, 'float');
hdr.op_user_48 = fread(fid, 1, 'float');
fseek(fid, 60, 'cof');
hdr.x_dim = fread(fid, 1, 'float');
hdr.y_dim = fread(fid, 1, 'float');
hdr.x_size = fread(fid, 1, 'float');
hdr.y_size = fread(fid, 1, 'float');
hdr.r_center = fread(fid, 1, 'float');
hdr.a_center = fread(fid, 1, 'float');
hdr.s_center = fread(fid, 1, 'float');
hdr.r_norm = fread(fid, 1, 'float');
hdr.a_norm = fread(fid, 1, 'float');
hdr.s_norm = fread(fid, 1, 'float');
fseek(fid, 336, 'cof');
hdr.tr = fread(fid, 1, 'int');
hdr.ti = fread(fid, 1, 'int');
hdr.te = fread(fid, 1, 'int');
fseek(fid, 432, 'cof');
hdr.frequency_direction = fread(fid, 1, 'short');
fseek(fid, 130, 'cof');
hdr.psd_name = fread(fid, 33, '*char');
fseek(fid, 84, 'cof');
hdr.coil_name = fread(fid, 17, '*char');
fseek(fid, 115, 'cof');
hdr.coil_name = fread(fid, 24, '*char');
end