% Read the header of a P file (version 24).
% liuhang, 2018/6/28

clear all;
Pfile = 'F:\sd\mri\pfile reconstruction\data\version 24\dicom_data\breast_coil\P50176.7';
fid=fopen(Pfile,'r', 'ieee-le');
% hdr = read_hdr_24(fid);

% function hdr = read_hdr_24(fid)
fseek(fid, 0, 'bof');
hdr.version = fread(fid, 1, 'float');
fseek(fid, 12, 'cof');
hdr.scan_date = deblank(fread(fid, [1, 10], '*char'));
DateNum= datevec(hdr.scan_date, 'mm/dd/yyyy');
DateNum(1)= DateNum(1)+ 1900;
hdr.scan_date = datestr(DateNum, 'mm/dd/yyyy');
clear DateNum;
hdr.scan_time = deblank( fread(fid, [1, 8], '*char'));
fseek(fid, 30, 'cof');
hdr.npasses = fread(fid, 1, 'short');
fseek(fid, 2, 'cof');
hdr.nslices = fread(fid, 1, 'ushort');
hdr.nechoes = fread(fid, 1, 'short');
fseek(fid, 2, 'cof');
hdr.nframes = fread(fid, 1, 'short');
fseek(fid, 4, 'cof');
hdr.frame_size = fread(fid, 1, 'ushort');
fseek(fid, 20, 'cof');
hdr.acq_x_res = fread(fid, 1, 'ushort');
hdr.acq_y_res = fread(fid, 1, 'short');
hdr.recon_x_res = fread(fid, 1, 'short');
hdr.recon_y_res = fread(fid, 1, 'short');
hdr.im_size = fread(fid, 1, 'short');
hdr.recon_z_res = fread(fid, 1, 'int');
fseek(fid, 84, 'cof');
hdr.start_rcv = fread(fid, 1, 'int16');
hdr.stop_rcv = fread(fid, 1, 'int16');
hdr.ncoils = hdr.stop_rcv - hdr.start_rcv + 1;
fseek(fid, 1440, 'cof');
hdr.bandwidth = fread(fid, 1, 'float');
hdr.data_size = fread(fid, 1, 'ulong');
hdr.ssp_save = fread(fid, 1, 'ulong');  
hdr.uda_save = fread(fid, 1, 'ulong');
% fseek(fid, 139680, 'cof');
% hdr.aps_r1 = fread(fid, 1, 'int');
% hdr.aps_r2 = fread(fid, 1, 'int');
% hdr.aps_tg = fread(fid, 1, 'int');
fseek(fid, 139680+12, 'cof');
fp_freq = ftell(fid);
hdr.aps_frequency = fread(fid, 1, 'uint')/1e7;
% hdr.scale_i = fread(fid, 1, 'float');
% hdr.scale_q = fread(fid, 1, 'float');
% fseek(fid, 276, 'cof');
% hdr.x_shim = fread(fid, 1, 'short');
% hdr.y_shim = fread(fid, 1, 'short');
% hdr.z_shim = fread(fid, 1, 'short');
% hdr.recon_enabled = fread(fid, 1, 'short');
fseek(fid, 8+276+8+1744, 'cof');
hdr.magnet_strength = fread(fid, 1, 'int')/1e4;
hdr.patient_weight = fread(fid, 1, 'int')/1e3;
% hdr.exam_timestamp = fread(fid, 1, 'int');
fseek(fid, 4+112, 'cof');
fp_ex_no = ftell(fid);
hdr.exam_number = fread(fid, 1, 'ushort');
fseek(fid, 18, 'cof');
hdr.patient_age = fread(fid, 1, 'short');
fseek(fid, 2, 'cof');
hdr.patient_sex = fread(fid, 1, 'short');
% fseek(fid, 2, 'cof');
% hdr.patient_trauma = fread(fid, 1, 'short');
% fseek(fid, 2, 'cof');
% hdr.study_status = fread(fid, 1, 'short');
fseek(fid, 8+70, 'cof');
% hdr.history = fread(fid, 257, '*char');
% hdr.referring_physicians_name = fread(fid, 65, '*char');
% hdr.radiologists_name = fread(fid, 65, '*char');
% hdr.operators_name = fread(fid, 65, '*char');
% hdr.exam_description = fread(fid, 65, '*char');
fseek(fid, 257+65*4, 'cof');
hdr.exam_type = deblank( fread(fid, [1, 3], '*char'));
hdr.system_id = deblank( fread(fid, [1, 9], '*char'));
fseek(fid, 22, 'cof');
hdr.hospital_name = deblank( fread(fid, [1, 33], '*char'));
fseek(fid, 24, 'cof');
hdr.service_id = deblank( fread(fid, [1, 16], '*char'));
fseek(fid, 100, 'cof');
hdr.patient_name = deblank( fread(fid, [1, 65], '*char'));
hdr.patient_id = deblank( fread(fid, [1, 65], '*char'));
% hdr.req_num = fread(fid, 17, '*char');
% hdr.date_of_birth = fread(fid, 9, '*char');
fseek(fid, 17+9+552, 'cof');
hdr.start_location = fread(fid, 1, 'float');
hdr.end_location = fread(fid, 1, 'float');
% fseek(fid, 352, 'cof');
% hdr.series_timestamp = fread(fid, 1, 'int');
fseek(fid, 352+4+206, 'cof');
hdr.series_number = fread(fid, 1, 'short');
fseek(fid, 138, 'cof');
hdr.series_description = deblank( fread(fid, [1, 65], '*char'));
fseek(fid, 21, 'cof');
hdr.protocol = deblank( fread(fid, [1, 25], '*char'));
hdr.start_ras = fread(fid, 1, 'char');
hdr.end_ras = fread(fid, 1, 'char');
fseek(fid, 1769, 'cof');
hdr.x_fov = fread(fid, 1, 'float')/10;
hdr.y_fov = fread(fid, 1, 'float')/10;
hdr.scan_duration = fread(fid, 1, 'float');
fp=ftell(fid);
hdr.thickness = fread(fid, 1, 'float')/10;
fseek(fid, 14, 'cof');
hdr.scanspacing = fread(fid, 1, 'float');
% hdr.scanspacing = fread(fid, [1,400], 'uint8');
% scanspacing找不到
fseek(fid, 360, 'cof');
hdr.x_dim = fread(fid, 1, 'float');   %N_hor, Number of pixels horizontally
hdr.y_dim = fread(fid, 1, 'float');   %N_ver, Number of pixels vertically
hdr.x_size = fread(fid, 1, 'float');
hdr.y_size = fread(fid, 1, 'float');
hdr.r_center = fread(fid, 1, 'float');
hdr.a_center = fread(fid, 1, 'float');
hdr.s_center = fread(fid, 1, 'float');
hdr.r_norm = fread(fid, 1, 'float');
hdr.a_norm = fread(fid, 1, 'float');
hdr.s_norm = fread(fid, 1, 'float');
hdr.x_tl = fread(fid, 1, 'float');
hdr.y_tl = fread(fid, 1, 'float');
hdr.z_tl = fread(fid, 1, 'float');
hdr.x_tr = fread(fid, 1, 'float');
hdr.y_tr = fread(fid, 1, 'float');
hdr.z_tr = fread(fid, 1, 'float');
hdr.x_br = fread(fid, 1, 'float');
hdr.y_br = fread(fid, 1, 'float');
hdr.z_br = fread(fid, 1, 'float');
fseek(fid, 300, 'cof');
hdr.tr = fread(fid, 1, 'int')/1e3;
hdr.ti = fread(fid, 1, 'int')/1e3;
hdr.te = fread(fid, 1, 'int')/1e3;
fseek(fid, 300, 'cof');
hdr.matx = fread(fid, 1, 'integer*2');
hdr.maty = fread(fid, 1, 'integer*2');
fseek(fid, 128, 'cof');
hdr.frequency_direction = fread(fid, 1, 'short');
fseek(fid, 130, 'cof');
hdr.psd_name = deblank( fread(fid, [1, 33], '*char'));
fseek(fid, 84, 'cof');
hdr.coil_name = deblank( fread(fid, [1, 17], '*char'));   %最后几个字符乱码
fseek(fid, 115, 'cof');
hdr.long_coil_name = deblank( fread(fid, [1, 24], '*char'));

% end